### ISSUE TITLE
老师，运行不起来，报了个错，麻烦看下

### ISSUE THREAD

**Issue by darren-xia** [an-Underpriviliged-ZJUer/Kaleidoscope#4]
C:\Users\夏小毛\AppData\Local\Programs\Python\Python311\python.exe D:\Kaleidoscope\TikTokDetect.py 
Traceback (most recent call last):
  File "D:\Kaleidoscope\TikTokDetect.py", line 1, in <module>
    import MyUtils
  File "D:\Kaleidoscope\MyUtils\__init__.py", line 16, in <module>
    import PySimpleGUI
ModuleNotFoundError: No module named 'PySimpleGUI'

**Comment by an-Underpriviliged-ZJUer** [comment]
pip install pysimplegui
...这个还挺基础的，可以花点时间百度了解一下pip install
